rootProject.name = 'MQuran'

include ':app'

// Monorepo: Use root node_modules instead of app-level node_modules
def nodeModulesPath = new File(rootProject.projectDir, "../../../node_modules")

// Include React Native Gradle Plugin
includeBuild(new File(nodeModulesPath, "@react-native/gradle-plugin"))
